workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      android: true
    scripts:
      - name: Clean and build
        script: |
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
